version: '3'

services:
  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ~/volume/influxdb/data:/var/lib/influxdb2
      - ~/volume/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: xxxxxxxxxxx
      DOCKER_INFLUXDB_INIT_ORG: xxx-org
      DOCKER_INFLUXDB_INIT_BUCKET: xxxx-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: xxxxxxxxxxx